# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "floppy" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "virtio_gpu" ];
  boot.kernelParams = [ "noapic" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a3bba0a4-e351-42b9-8ffe-fc4f960a7c95";
      fsType = "ext4";
    };

  swapDevices = [ ];

	hardware.cpu.intel.updateMicrocode = true;
	hardware.enableRedistributableFirmware = true;
	# powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

