surfshark_auth: ENC[AES256_GCM,data:ucpWxAPcw2G8ek76sbIPiQDarE0L9tzdUaS37MO+Z8IqBdZIuPEW1GrNfRgyfLli5K0=,iv:43l7mLs3mXrdI2FzvRcQg6QzeKZTxfUdaujOaWYfhNc=,tag:rG9N/SE7Y0t1o/khnNo+Cw==,type:str]
sops:
    age:
        - recipient: age1muvxa44trrasxgjytwpzpl6zggzu287n0jw6j897xxxk5ytrheyq3csd8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDU3bWt6eEliRVVhVzZz
            ckd4eTRaR2RIcDhJWTdnS3MxQWovNHlkaHprCjRScm00YnUyUjl5UlAxazNmKzh6
            V0JiRWdlaVFQQkdncmlJS1hDbWNzUU0KLS0tIHI0SzFuc3BjeDFQQ29WV1NtNlM2
            dmlGWnlNbnBoOUJiazQ1Q255WEFTbDQKLvavlqOCqAvnmjzJfgGJVZsHwC7KvUrL
            IUN1wsV0b/yz6bqenOATGOc9QwXu6cT0MDYKkpjJricCC0Fob00ZHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T03:31:19Z"
    mac: ENC[AES256_GCM,data:/BV0u/8N9s5jghlCgc7ceG83nhMVYYyqAvfW5ytu57aLCC1Rk7NVE3HkQphpyECzKd3uRvqxh/HhfnaRDOd0/gt9yPCRVaqdjPfTBS4klq0U+P+PhKWW19pEBblyhdv1mlOu1TvQoemTS/1jKIe/0ZUY6z17u1C2cCMRIjPbpCk=,iv:1RXzoOrsDF1qIy5uOMzzOPJOtzm8342F2lHtOfRqTkw=,tag:9UQ+eRWnABFZKG94NXkzcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
