game:
  exe: Cemu.exe
  prefix: ~/Games/Cemu
system:
  disable_compositor: true
  env:
    R600_DEBUG: nohyperz
    __GL_THREADED_OPTIMIZATIONS: '1'
    mesa_glthread: 'true'
    vblank_mode: '0'
  gamemode: false
  prefix_command: ''
wine:
  overrides:
    dbghelp: native,builtin
    mscoree: disabled
    mshtml: disabled
  version: lutris-6.21-6-x86_64
