game:
  exe: /media/Drive/Games/Crash Bandicoot N. Sane Trilogy/CrashBandicootNSaneTrilogy.exe
  prefix: /media/Drive/Games/tmp
game_slug: crash-bandicoot-n-sane-trilogy
name: "Crash Bandicoot\u2122 N. Sane Trilogy"
requires: null
script:
  files:
  - setupfile: N/A:Select the setup file
  game:
    exe: _xXx_AUTO_WIN32_xXx_
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      env:
        LC_ALL: ''
      executable: /media/Drive/Torrent/Crash Bandicoot N. Sane Trilogy [FitGirl Repack]/setup.exe
      prefix: /media/Drive/Games/tmp
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
  system:
    env:
      LC_ALL: ''
slug: crash-bandicoot-n-sane-trilogy-setup
system:
  env:
    LC_ALL: ''
  locale: ''
  prefix_command: ''
variables: {}
version: Setup file
wine: {}
year: null
