game:
  exe: /media/Drive/Games/GTA Trilogy The Definitive Edition/GTA III - Definitive
    Edition/Gameface/Binaries/Win64/LibertyCity.exe
  prefix: /media/Drive/Games/GTA Trilogy The Definitive Edition/GTA III - Definitive
    Edition
