game:
  exe: /media/Drive/Games/GTA Trilogy The Definitive Edition/GTA San Andreas - Definitive
    Edition/Gameface/Binaries/Win64/SanAndreas.exe
  prefix: /media/Drive/Games/GTA Trilogy The Definitive Edition/GTA San Andreas -
    Definitive Edition
