game:
  exe: /media/Drive/Games/GUILTY GEAR -STRIVE-/RED/Binaries/Win64/GGST-Win64-Shipping.exe
  prefix: /media/Drive/Games/GUILTY GEAR -STRIVE-
game_slug: guilty-gear-strive-
name: GUILTY GEAR -STRIVE-
requires: null
script:
  files:
  - setupfile: N/A:Select the setup file
  game:
    exe: _xXx_AUTO_WIN32_xXx_
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      env:
        LC_ALL: ''
      executable: /media/Drive/Torrent/GUILTY GEAR -STRIVE- [FitGirl Repack]/setup.exe
      prefix: /media/Drive/tmp
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
  system:
    env:
      LC_ALL: ''
slug: guilty-gear-strive--setup
system:
  env:
    LC_ALL: ''
  locale: ''
  prefix_command: ''
variables: {}
version: Setup file
wine:
  version: GE-Proton8-32
year: null
