game:
  args: --locale=en_US --launch-product=league_of_legends --launch-patchline=live
  exe: /media/Drive/Games/league-of-legends/drive_c/Riot Games/Riot Client/RiotClientServices.exe
  prefix: /media/Drive/Games/league-of-legends
game_slug: league-of-legends
name: League of Legends
requires: null
script:
  files:
  - lol_installer: https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
  game:
    args: --locale=$INPUT_LOCALE --launch-product=league_of_legends --launch-patchline=live
    exe: $GAMEDIR/drive_c/Riot Games/Riot Client/RiotClientServices.exe
    prefix: $GAMEDIR
  installer:
  - input_menu:
      id: LOCALE
      options:
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      preselect: en_US
  - task:
      arch: win64
      prefix: /media/Drive/Games/league-of-legends
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-lol-8-27-x86_64/bin/wine
  - task:
      arch: win64
      args: /home/gerry/.cache/lutris/installer/league-of-legends/lol_installer/live.na.exe
      env:
        DXVK_LOG_LEVEL: none
        DXVK_STATE_CACHE_PATH: /media/Drive/Games/league-of-legends
        STAGING_SHARED_MEMORY: '1'
        WINE_LARGE_ADDRESS_AWARE: '1'
        __GL_SHADER_DISK_CACHE: '1'
        __GL_SHADER_DISK_CACHE_PATH: /media/Drive/Games/league-of-legends
      executable: /media/Drive/Games/league-of-legends/drive_c/windows/explorer.exe
      include_processes: explorer.exe
      prefix: /media/Drive/Games/league-of-legends
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-lol-8-27-x86_64/bin/wine
  - task:
      arch: win64
      prefix: /media/Drive/Games/league-of-legends
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-lol-8-27-x86_64/bin/wine
  - task:
      arch: win64
      key: GrabFullScreen
      path: HKEY_CURRENT_USER\Software\Wine\X11 Driver
      prefix: /media/Drive/Games/league-of-legends
      value: Y
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-lol-8-27-x86_64/bin/wine
  - task:
      arch: win64
      key: background
      path: HKEY_CURRENT_USER\Control Panel\Colors\
      prefix: /media/Drive/Games/league-of-legends
      type: REG_SZ
      value: 40 40 40
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-lol-8-27-x86_64/bin/wine
  system:
    env:
      DXVK_LOG_LEVEL: none
      DXVK_STATE_CACHE_PATH: $GAMEDIR
      STAGING_SHARED_MEMORY: 1
      WINE_LARGE_ADDRESS_AWARE: 1
      __GL_SHADER_DISK_CACHE: 1
      __GL_SHADER_DISK_CACHE_PATH: $GAMEDIR
  wine:
    MouseWarpOverride: enable
    dgvoodoo2: true
    version: wine-ge-lol-8-27-x86_64
slug: league-of-legends-standard-na
system:
  env:
    DXVK_LOG_LEVEL: none
    DXVK_STATE_CACHE_PATH: /media/Drive/Games/league-of-legends
    STAGING_SHARED_MEMORY: '1'
    WINE_LARGE_ADDRESS_AWARE: '1'
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /media/Drive/Games/league-of-legends
  locale: ''
  prefix_command: ''
variables: {}
version: Standard (NA)
wine:
  MouseWarpOverride: enable
  dgvoodoo2: true
  version: wine-ge-lol-8-27-x86_64
year: 2009
