game:
  args: -g "C:\wiiu\games\fk-mk8.wud" -f
  exe: Cemu.exe
  prefix: ~/Games/Cemu
system:
  disable_compositor: true
  env:
    R600_DEBUG: nohyperz
    __GL_THREADED_OPTIMIZATIONS: '1'
    mesa_glthread: 'true'
    vblank_mode: '0'
wine:
  overrides:
    dbghelp: native,builtin
    mscoree: disabled
    mshtml: disabled
  version: lutris-6.21-6-x86_64
