game:
  exe: /media/Drive/Games/Mega Man 11/game.exe
  prefix: /media/Drive/Games/Mega Man 11
game_slug: mega-man-11
name: Mega Man 11
requires: null
script:
  files:
  - setupfile: N/A:Select the setup file
  game:
    exe: _xXx_AUTO_WIN32_xXx_
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      env:
        LC_ALL: en_US.utf8
      executable: /media/Drive/Torrent/Mega Man 11 [FitGirl Repack]/setup.exe
      prefix: /media/Drive/Torrent/megaman-install
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
  system:
    env:
      LC_ALL: en_US.utf8
slug: mega-man-11-setup
system:
  env:
    LC_ALL: en_US.utf8
  locale: ''
  prefix_command: ''
variables: {}
version: Setup file
wine:
  version: wine-ge-8-26-x86_64
year: null
