game:
  exe: /media/Drive/Games/NINJA GAIDEN - Master Collection/Ninja Gaiden 3/NINJA GAIDEN
    3 Razor's Edge.exe
  prefix: /media/Drive/Games/NINJA GAIDEN - Master Collection
system:
  locale: ''
wine: {}
