game:
  exe: /media/Drive/Games/Resident Evil 5 Gold Edition/Launcher.exe
  prefix: /media/Drive/Games/Resident Evil 5 Gold Edition
game_slug: resident-evil-5
name: Resident Evil 5
script:
  files:
  - setupfile: N/A:Select the setup file
  game:
    exe: _xXx_AUTO_WIN32_xXx_
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      env:
        LC_ALL: ''
      executable: /media/Drive/Torrent/Resident Evil 5 Gold Edition - [DODI Repack]/Setup.exe
      prefix: /home/gerry/tmp
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
  system:
    env:
      LC_ALL: ''
slug: resident-evil-5-setup
system:
  env:
    LC_ALL: ''
version: Setup file
