game:
  exe: /media/Drive/Games/Sekiro - Shadows Die Twice/sekiro.exe
  prefix: /media/Drive/Games/Sekiro - Shadows Die Twice
game_slug: sekiro-shadows-die-twice-goty-edition
name: "Sekiro\u2122: Shadows Die Twice - GOTY Edition"
requires: null
script:
  files:
  - setupfile: N/A:Select the setup file
  game:
    exe: _xXx_AUTO_WIN32_xXx_
    prefix: $GAMEDIR
  installer:
  - task:
      arch: win64
      env:
        LC_ALL: ''
      executable: /media/Drive/Torrent/Sekiro - Shadows Die Twice [FitGirl Repack]/setup.exe
      prefix: /media/Drive/Games/sekiro-shadows-die-twice-goty-edition
      wine_path: /home/gerry/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine
  system:
    env:
      LC_ALL: ''
slug: sekiro-shadows-die-twice-goty-edition-setup
system:
  env:
    LC_ALL: ''
  locale: ''
  prefix_command: ''
variables: {}
version: Setup file
wine:
  version: GE-Proton9-1
year: null
